packages:
    - 'packages/*'

overrides:
    playwright: $playwright
    typescript: $typescript

packageExtensions:
    '@vitest/browser':
        peerDependencies:
            '@vitest/runner': '*'

allowBuilds:
    esbuild: true
