// JavaScript Actions example - Executing JS actions in PDF form fields
//
// PDF forms generated by Adobe Acrobat and LiveCycle often include JavaScript
// actions for formatting, validation, and field calculations. The
// PdfJavaScriptEngine executes these automatically when setting field values,
// with built-in support for common Acrobat JS functions.

import { PdfArray } from 'pdf-lite/core/objects/pdf-array'
import { PdfBoolean } from 'pdf-lite/core/objects/pdf-boolean'
import { PdfDictionary } from 'pdf-lite/core/objects/pdf-dictionary'
import { PdfIndirectObject } from 'pdf-lite/core/objects/pdf-indirect-object'
import { PdfName } from 'pdf-lite/core/objects/pdf-name'
import { PdfNumber } from 'pdf-lite/core/objects/pdf-number'
import { PdfObjectReference } from 'pdf-lite/core/objects/pdf-object-reference'
import { PdfStream } from 'pdf-lite/core/objects/pdf-stream'
import { PdfString } from 'pdf-lite/core/objects/pdf-string'
import { PdfDocument } from 'pdf-lite/pdf/pdf-document'
import { PdfJavaScriptEngine } from 'pdf-lite/acroform/js/pdf-js-engine-impl'
import fs from 'fs/promises'

const tmpFolder = `${import.meta.dirname}/tmp`
await fs.mkdir(tmpFolder, { recursive: true })

// ============================================
// Helpers
// ============================================

function createPage(
    contentStreamRef: PdfObjectReference,
): PdfIndirectObject<PdfDictionary> {
    const d = new PdfDictionary()
    d.set('Type', new PdfName('Page'))
    d.set(
        'MediaBox',
        new PdfArray([
            new PdfNumber(0),
            new PdfNumber(0),
            new PdfNumber(612),
            new PdfNumber(792),
        ]),
    )
    d.set('Contents', contentStreamRef)
    return new PdfIndirectObject({ content: d })
}

function createPages(
    pages: PdfIndirectObject<PdfDictionary>[],
): PdfIndirectObject<PdfDictionary> {
    const d = new PdfDictionary()
    d.set('Type', new PdfName('Pages'))
    d.set('Kids', new PdfArray(pages.map((x) => x.reference)))
    d.set('Count', new PdfNumber(pages.length))
    return new PdfIndirectObject({ content: d })
}

function createCatalog(
    pagesRef: PdfObjectReference,
): PdfIndirectObject<PdfDictionary> {
    const d = new PdfDictionary()
    d.set('Type', new PdfName('Catalog'))
    d.set('Pages', pagesRef)
    return new PdfIndirectObject({ content: d })
}

/** Create a text field with an optional JavaScript format action. */
function createTextField(
    fieldName: string,
    pageRef: PdfObjectReference,
    rect: [number, number, number, number],
    jsFormatCode?: string,
    jsCalcCode?: string,
): PdfIndirectObject<PdfDictionary> {
    const d = new PdfDictionary()
    d.set('Type', new PdfName('Annot'))
    d.set('Subtype', new PdfName('Widget'))
    d.set('FT', new PdfName('Tx'))
    d.set('T', new PdfString(fieldName))
    d.set(
        'Rect',
        new PdfArray([
            new PdfNumber(rect[0]),
            new PdfNumber(rect[1]),
            new PdfNumber(rect[2]),
            new PdfNumber(rect[3]),
        ]),
    )
    d.set('F', new PdfNumber(4))
    d.set('P', pageRef)
    d.set('DA', new PdfString('/Helv 12 Tf 0 g'))

    // Add /AA (additional actions) dictionary with JS format/calculate actions
    if (jsFormatCode || jsCalcCode) {
        const aa = new PdfDictionary()
        if (jsFormatCode) {
            const fmtAction = new PdfDictionary()
            fmtAction.set('S', new PdfName('JavaScript'))
            fmtAction.set('JS', new PdfString(jsFormatCode))
            aa.set('F', fmtAction)
        }
        if (jsCalcCode) {
            const calcAction = new PdfDictionary()
            calcAction.set('S', new PdfName('JavaScript'))
            calcAction.set('JS', new PdfString(jsCalcCode))
            aa.set('C', calcAction)
        }
        d.set('AA', aa)
    }

    return new PdfIndirectObject({ content: d })
}

// ============================================
// Build a PDF with JS-powered form fields
// ============================================

const document = new PdfDocument()

// Font
const font = new PdfDictionary()
font.set('Type', new PdfName('Font'))
font.set('Subtype', new PdfName('Type1'))
font.set('BaseFont', new PdfName('Helvetica'))
const fontObj = new PdfIndirectObject({ content: font })
document.add(fontObj)

// Resources
const resources = new PdfDictionary()
const fontDict = new PdfDictionary()
fontDict.set('F1', fontObj.reference)
resources.set('Font', fontDict)
const resourcesObj = new PdfIndirectObject({ content: resources })
document.add(resourcesObj)

// Content stream with labels
const contentStream = new PdfIndirectObject({
    content: new PdfStream({
        header: new PdfDictionary(),
        original: `BT
/F1 18 Tf 72 720 Td (Invoice - JS Actions Demo) Tj
/F1 12 Tf 0 -50 Td (Price:) Tj
0 -30 Td (Quantity:) Tj
0 -30 Td (Total:) Tj
0 -40 Td (Phone:) Tj
ET `,
    }),
})
document.add(contentStream)

// Page
const page = createPage(contentStream.reference)
page.content.set('Resources', resourcesObj.reference)
document.add(page)

// Form fields with JavaScript actions:

// Price field — formats as currency via AFNumber_Format
const priceField = createTextField(
    'Price',
    page.reference,
    [150, 655, 350, 675],
    'AFNumber_Format(2, 0, 0, 0, "$", true)',
)
document.add(priceField)

// Quantity field — plain number format
const qtyField = createTextField(
    'Quantity',
    page.reference,
    [150, 625, 350, 645],
    'AFNumber_Format(0, 0, 0, 0, "", false)',
)
document.add(qtyField)

// Total field — calculated as Price * Quantity via AFSimple_Calculate
const totalField = createTextField(
    'Total',
    page.reference,
    [150, 595, 350, 615],
    'AFNumber_Format(2, 0, 0, 0, "$", true)',
    'AFSimple_Calculate("PRD", ["Price", "Quantity"])',
)
document.add(totalField)

// Phone field — formatted via AFSpecial_Format (phone)
const phoneField = createTextField(
    'Phone',
    page.reference,
    [150, 555, 350, 575],
    'AFSpecial_Format(2)',
)
document.add(phoneField)

// Annotations on page
page.content.set(
    'Annots',
    new PdfArray([
        priceField.reference,
        qtyField.reference,
        totalField.reference,
        phoneField.reference,
    ]),
)

// Pages / catalog
const pages = createPages([page])
page.content.set('Parent', pages.reference)
document.add(pages)

const catalog = createCatalog(pages.reference)

// AcroForm with fields and calculation order
const acroForm = new PdfDictionary()
acroForm.set(
    'Fields',
    new PdfArray([
        priceField.reference,
        qtyField.reference,
        totalField.reference,
        phoneField.reference,
    ]),
)
// Calculation order — Total depends on Price and Quantity
acroForm.set('CO', new PdfArray([totalField.reference]))
acroForm.set('NeedAppearances', new PdfBoolean(true))

// Form default resources
const formResources = new PdfDictionary()
const formFontDict = new PdfDictionary()
const helvetica = new PdfDictionary()
helvetica.set('Type', new PdfName('Font'))
helvetica.set('Subtype', new PdfName('Type1'))
helvetica.set('BaseFont', new PdfName('Helvetica'))
const helveticaObj = new PdfIndirectObject({ content: helvetica })
document.add(helveticaObj)
formFontDict.set('Helv', helveticaObj.reference)
formResources.set('Font', formFontDict)
acroForm.set('DR', formResources)
acroForm.set('DA', new PdfString('/Helv 12 Tf 0 g'))

const acroFormObj = new PdfIndirectObject({ content: acroForm })
document.add(acroFormObj)
catalog.content.set('AcroForm', acroFormObj.reference)
document.add(catalog)
document.trailerDict.set('Root', catalog.reference)

await document.finalize()
await fs.writeFile(`${tmpFolder}/js-actions-form.pdf`, document.toBytes())
console.log('Created js-actions-form.pdf with JavaScript action fields')

// ============================================
// Fill the form with the JS engine enabled
// ============================================

const formBytes = await fs.readFile(`${tmpFolder}/js-actions-form.pdf`)
const filledDoc = await PdfDocument.fromBytes([formBytes])
const form = filledDoc.acroform!

// Attach the JS engine with a field value resolver for AFSimple_Calculate
form.jsEngine = new PdfJavaScriptEngine({
    getFieldValue: (name) => {
        const field = form.fields.find((f) => f.name === name)
        return field?.value ?? ''
    },
})

// Set values — JS format actions fire automatically
form.setValues({
    Price: '49.99',
    Quantity: '3',
    Phone: '5551234567',
})

// Print resulting values (after JS actions have run)
console.log('\nField values after JS actions:')
for (const field of form.fields) {
    console.log(`  ${field.name}: "${field.value}"`)
}
// Expected output:
//   Price: "$49.99"
//   Quantity: "3"
//   Total: "$149.97"  (calculated via AFSimple_Calculate PRD)
//   Phone: "(555) 123-4567"  (formatted via AFSpecial_Format)

await fs.writeFile(`${tmpFolder}/js-actions-filled.pdf`, filledDoc.toBytes())
console.log('\nCreated js-actions-filled.pdf with JS-formatted values')
