// Test appearance generation for AcroForm text fields
// This demonstrates how to generate appearance streams when filling PDF forms
// to avoid the PDF viewer prompting to save changes

import { PdfDocument } from '../packages/pdf-lite/src/pdf/pdf-document.js'
import fs from 'fs/promises'

const tmpFolder = `${import.meta.dirname}/tmp`
await fs.mkdir(tmpFolder, { recursive: true })

// Use the form created by the modify-acroform example
const formPath = `${import.meta.dirname}/../examples/tmp/form-empty.pdf`

try {
    // Check if the form exists
    await fs.access(formPath)
} catch {
    console.error(
        'Form not found. Please run the examples/005-modify-acroform.ts example first to create the form.',
    )
    process.exit(1)
}

// Read the empty form PDF
const emptyFormBytes = await fs.readFile(formPath)
const document = await PdfDocument.fromBytes([emptyFormBytes])

const acroform = await document.acroForm.read()
if (!acroform) {
    throw new Error('No AcroForm found in the document')
}

console.log('Testing appearance generation for AcroForm text fields...\n')

// Test 1: Fill fields WITH appearance generation (no needsAppearances flag)
console.log('Test 1: Filling fields with generated appearances')
console.log('----------------------------------------------')

// Fill in the form fields
acroform.importData({
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+1 (555) 987-6543',
    subscribe: 'Yes',
})

// Generate appearances for text fields
let generatedCount = 0
for (const field of acroform.fields) {
    if (field.fieldType === 'Tx' && field.value) {
        const success = field.generateAppearance()
        if (success) {
            generatedCount++
            console.log(
                `  ✓ Generated appearance for field: ${field.name} = "${field.value}"`,
            )
        }
    }
}

console.log(`\nGenerated ${generatedCount} appearance streams`)

// Important: Set needsAppearances to false since we're providing appearances
acroform.needAppearances = false
console.log('  ✓ Set needsAppearances = false')

// Write the form - this automatically creates the appearance indirect objects
await document.acroForm.write(acroform)

// Save the filled form with appearances
const outputPath = `${tmpFolder}/form-with-appearances.pdf`
await fs.writeFile(outputPath, document.toBytes())
console.log(`\n✓ Saved to: ${outputPath}`)

// Test 2: Compare with needsAppearances flag (for demonstration)
console.log('\n\nTest 2: Filling fields WITHOUT generated appearances')
console.log('-----------------------------------------------------')

const document2 = await PdfDocument.fromBytes([emptyFormBytes])
const acroform2 = await document2.acroForm.read()
if (!acroform2) {
    throw new Error('No AcroForm found in the document')
}

acroform2.importData({
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1 (555) 123-4567',
    subscribe: 'Off',
})

// Set needsAppearances flag instead of generating appearances
acroform2.needAppearances = true
console.log(
    '  ✓ Set needsAppearances = true (viewer will generate appearances)',
)

await document2.acroForm.write(acroform2)

const outputPath2 = `${tmpFolder}/form-needs-appearances.pdf`
await fs.writeFile(outputPath2, document2.toBytes())
console.log(`  ✓ Saved to: ${outputPath2}`)

console.log('\n\nComparison:')
console.log('===========')
console.log(
    '1. form-with-appearances.pdf:     Appearances generated by pdf-lite',
)
console.log('   - Opens without asking to save')
console.log('   - Fields display correctly immediately')
console.log('')
console.log('2. form-needs-appearances.pdf:    needsAppearances = true')
console.log('   - PDF viewer generates appearances on open')
console.log('   - Asks to save when closing (because viewer modified the PDF)')
console.log('')
console.log('Result: Using generateAppearance() avoids the save prompt!')
